src/Opserver.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Opserver.Data.Dashboard;
using Opserver.Helpers;
using Opserver.Views.Dashboard;

namespace Opserver.Controllers
{
    [OnlyAllow(DashboardRoles.Viewer)]
    public partial class DashboardController : StatusController<DashboardModule>
    {
        public DashboardController(DashboardModule module, IOptions<OpserverSettings> settings) : base(module, settings) { }

        [DefaultRoute("dashboard")]
        public ActionResult Dashboard(string q)
        {
            var vd = new DashboardModel
            {
                Nodes = GetNodes(q),
                ErrorMessages = Module.ProviderExceptions.ToList(),
                Filter = q,
                IsStartingUp = Module.AnyDoingFirstPoll
            };
            return Request.IsAjax() ? PartialView("Dashboard.Table", vd) : (ActionResult)View("Dashboard.Table", vd);
        }

        private List<Node> GetNodes(string search) =>
            search.HasValue()
            ? Module.AllNodes.Where(n => n.SearchString?.IndexOf(search, StringComparison.InvariantCultureIgnoreCase) > -1).ToList()
            : Module.AllNodes.ToList();

        [Route("dashboard/json")]
        public ActionResult DashboardJson()
        {
            var categories = Module.AllNodes
                .GroupBy(n => n.Category)
                .Where(g => g.Any() && (g.Key != DashboardCategory.Unknown || Module.Settings.ShowOther))
                .OrderBy(g => g.Key.Index);

            var resultCategories = categories.Select(g =>
            {
                var c = g.Key;
                var cNodes = g.OrderBy(n => n.PrettyName);
                var nodes = cNodes.Select(n => new
                {
                    n.Id,
                    Status = n.RawClass(),
                    Class = n.RowClass().Nullify() + (n.IsVM ? " virtual-machine" : null),
                    Search = n.SearchString,
                    Name = n.PrettyName,
                    Label = n.IsVM ? "Virtual Machine hosted on " + n.VMHost.PrettyName + " " : null + "Last Updated:" + n.LastSync?.ToRelativeTime(),
                    AppText = n.ApplicationCPUTextSummary,
                    CpuStatus = n.CPUMonitorStatus().RawClass(),
                    CPU = n.CPULoad,
                    AppMemory = n.ApplicationMemoryTextSummary.Nullify(),
                    MemStatus = n.MemoryMonitorStatus().RawClass().Nullify(),
                    MemPercent = n.PercentMemoryUsed > 0 ? n.PercentMemoryUsed : null,
                    MemText = $"{n.PrettyMemoryUsed()} / {n.PrettyTotalMemory()}({n.PercentMemoryUsed?.ToString("n2")}%)",
                    NetPretty = n.PrettyTotalNetwork(),
                    DiskPercent = n.Volumes?.Select(v => v.PercentUsed).Where(p => p.HasValue).DefaultIfEmpty(0).Max(),
                    Disks = n.Volumes?.Select(v => new
                    {
                        Name = v.PrettyName,
                        Status = v.RawClass(),
                        Tooltip = $"{v.PrettyName}: {v.PercentUsed?.ToString("n2")}% used ({v.PrettyUsed}/{v.PrettySize})",
                        PercentUsed = v.PercentUsed?.ToString("n2")
                    })
                });
                return new
                {
                    c.Name,
                    Nodes = nodes
                };
            }).ToList();
            return Json(new
            {
                Module.HasData,
                Categories = resultCategories
            });
        }

        [Route("dashboard/node")]
        public ActionResult Node([DefaultValue(CurrentStatusTypes.Stats)]CurrentStatusTypes view, string node = null)
        {
            var vd = new NodeModel
            {
                CurrentNode = Module.GetNodeByName(node),
                CurrentStatusType = view
            };

            return View("Node", vd);
        }

        [Route("dashboard/node/summary/{type}")]
        public ActionResult InstanceSummary(string node, string type)
        {
            var n = Module.GetNodeByName(node);
            return type switch
            {
                "hardware" => PartialView("Node.Hardware", n),
                "network" => PartialView("Node.Network", n),
                _ => ContentNotFound("Unknown summary view requested"),
            };
        }

        [Route("dashboard/graph/{nodeId}/{type}")]
        [Route("dashboard/graph/{nodeId}/{type}/{subId?}")]
        public async Task<ActionResult> NodeGraph(string nodeId, string type, string subId)
        {
            var n = Module.GetNodeById(nodeId);
            var vd = new NodeGraphModel
            {
                Node = n,
                Type = type
            };

            if (n != null)
            {
                switch (type)
                {
                    case NodeGraphModel.KnownTypes.Live:
                        await PopulateModel(vd, NodeGraphModel.KnownTypes.CPU, subId);
                        await PopulateModel(vd, NodeGraphModel.KnownTypes.Memory, subId);
                        //await PopulateModel(vd, NodeGraphModel.KnownTypes.Network, subId);
                        break;
                    case NodeGraphModel.KnownTypes.CPU:
                    case NodeGraphModel.KnownTypes.Memory:
                    case NodeGraphModel.KnownTypes.Network:
                    case NodeGraphModel.KnownTypes.Volume:
                    case NodeGraphModel.KnownTypes.VolumePerformance:
                        await PopulateModel(vd, type, subId);
                        break;
                }
            }

            return PartialView("Node.Graph", vd);
        }

        private static async Task PopulateModel(NodeGraphModel vd, string type, string subId)
        {
            var n = vd.Node;
            switch (type)
            {
                case NodeGraphModel.KnownTypes.CPU:
                    vd.Title = "CPU Utilization (" + (n.PrettyName ?? "Unknown") + ")";
                    vd.CpuData = await GraphController.CPUData(n, summary: true);
                    break;
                case NodeGraphModel.KnownTypes.Memory:
                    vd.Title = "Memory Utilization (" + (n.TotalMemory?.ToSize() ?? "Unknown Max") + ")";
                    vd.MemoryData = await GraphController.MemoryData(n, summary: true);
                    break;
                case NodeGraphModel.KnownTypes.Network:
                    if (subId.HasValue())
                    {
                        var i = vd.Node.GetInterface(subId);
                        vd.Interface = i;
                        vd.Title = "Network Utilization (" + (i?.PrettyName ?? "Unknown") + ")";
                        vd.NetworkData = await GraphController.NetworkData(i, summary: true);
                    }
                    else
                    {
                        vd.Title = "Network Utilization (" + (n.PrettyName ?? "Unknown") + ")";
                        vd.NetworkData = await GraphController.NetworkData(n, summary: true);
                    }
                    break;
                case NodeGraphModel.KnownTypes.Volume:
                    {
                        var v = vd.Node.GetVolume(subId);
                        vd.Volume = v;
                        vd.Title = "Volume Usage (" + (v?.PrettyName ?? "Unknown") + ")";
                        // TODO: Volume data
                    }
                    break;
                case NodeGraphModel.KnownTypes.VolumePerformance:
                    if (subId.HasValue())
                    {
                        var v = vd.Node.GetVolume(subId);
                        vd.Volume = v;
                        vd.Title = "Volume Performance (" + (v?.PrettyName ?? "Unknown") + ")";
                        vd.VolumePerformanceData = await GraphController.VolumePerformanceData(v, summary: true);
                    }
                    else
                    {
                        vd.Title = "Volume Performance (" + (n.PrettyName ?? "Unknown") + ")";
                        vd.VolumePerformanceData = await GraphController.VolumePerformanceData(n, summary: true);
                    }
                    break;
            }
        }
    }
}

src/Opserver.Web/Controllers/ElasticController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Opserver.Data.Elastic;
using Opserver.Helpers;
using Opserver.Views.Elastic;

namespace Opserver.Controllers
{
    [OnlyAllow(ElasticRoles.Viewer)]
    public class ElasticController : StatusController<ElasticModule>
    {
        public ElasticController(ElasticModule module, IOptions<OpserverSettings> settings) : base(module, settings) { }

        [DefaultRoute("elastic")]
        public ActionResult Dashboard()
        {
            var vd = new DashboardModel
            {
                Clusters = Module.Clusters,
                View = DashboardModel.Views.AllClusters,
                DisplayMode = DashboardModel.DisplayModes.InterestingOnly
            };
            return View("AllClusters", vd);
        }

        [Route("elastic/cluster")]
        public ActionResult Cluster(string cluster, string node)
        {
            var vd = GetViewData(cluster, node);
            vd.View = DashboardModel.Views.Cluster;
            return View("Cluster", vd);
        }

        [Route("elastic/node")]
        public ActionResult Node(string cluster, string node)
        {
            var vd = GetViewData(cluster, node);
            vd.View = DashboardModel.Views.Node;
            return View("Node", vd);
        }

        [Route("elastic/node/modal/{type}")]
        public ActionResult NodeModal(string cluster, string node, string type)
        {
            var vd = GetViewData(cluster, node);
            return type switch
            {
                "settings" => PartialView("Node.Settings", vd),
                _ => ContentNotFound("Unknown modal view requested"),
            };
        }

        [Route("elastic/cluster/modal/{type}")]
        public ActionResult ClusterModal(string cluster, string node, string type)
        {
            var vd = GetViewData(cluster, node);
            return type switch
            {
                "indexes" => PartialView("Cluster.Indexes", vd),
                _ => ContentNotFound("Unknown modal view requested"),
            };
        }

        [Route("elastic/index/modal/{type}")]
        public ActionResult IndexModal(string cluster, string node, string index, string type)
        {
            var vd = GetViewData(cluster, node, index);
            return type switch
            {
                "shards" => PartialView("Cluster.Shards", vd),
                _ => ContentNotFound("Unknown modal view requested"),
            };
        }

        private DashboardModel GetViewData(string cluster, string node = null, string index = null)
        {
            // Cluster names are not unique, names + node names should be though
            // If we see too many people with crazy combos, then node GUIDs it is.
            var cc = Module.Clusters.Find(
                c => string.Equals(c.Name, cluster, StringComparison.InvariantCultureIgnoreCase)
                  && (node.IsNullOrEmpty() || (c.Nodes.Data?.Get(node) != null)));
            var cn = cc?.Nodes.Data.Get(node);

            return new DashboardModel
            {
                Clusters = Module.Clusters,
                CurrentNodeName = node,
                CurrentClusterName = cc?.Name,
                CurrentIndexName = index,
                CurrentCluster = cc,
                CurrentNode = cn
            };
        }

        [Route("elastic/indexes")]
        public ActionResult Indexes(string cluster, string node, string guid)
        {
            var vd = GetViewData(cluster, node ?? guid);
            vd.View = DashboardModel.Views.Indexes;
            return View("Indexes", vd);
        }

        [Route("elastic/reroute/{type}")]
        public ActionResult Reroute(string type) //, string index, int shard, string node)
        {
            bool result = false;
            switch (type)
            {
                case "assign":
                    result = true;
                    break;
                case "cancel":
                    result = true;
                    break;
            }
            return Json(result);
        }
    }
}

src/Opserver.Web/Controllers/HubController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Opserver.Data.Dashboard;
using Opserver.Helpers;
using Opserver.Models;
using Opserver.Views.Hub;

namespace Opserver.Controllers
{
    [OnlyAllow(Roles.Authenticated)]
    public class HubController : StatusController<DashboardModule>
    {
        public HubController(DashboardModule module, IOptions<OpserverSettings> settings) : base(module, settings) { }

        [Route("hub"), Route("headsup"), AlsoAllow(Roles.InternalRequest)]
        public ActionResult Index()
        {
            var vd = new HubModel();
            return View(vd);
        }
    }
}

src/Opserver.Web/Views/Hub/Dashboard.Node.cshtml
@using Opserver.Data.Dashboard
@inject DashboardModule Dashboard
@model Node
@{
    var s = Model;
}
@functions
{
    public string GetItemClass(Node s)
    {
        var prefix = s.IsVM ? "virtual-machine " : "";
        return prefix + s.RowClass();
    }
    string Graph(Node s, string type)
    {
        if (!Dashboard.HasData)
        {
            <div class="text-muted">No Data Available</div>
        }
        else
        {
            <img class="js-dashboard-spark" src="@Url.Content("~/graph/")@type.ToLower()/spark?id=@s.Id" alt="" data-id="@s.Id" data-type="@type" data-node="@s.PrettyName" />
        }
        return null;
    }
}
<div class="item dashboard @s.TextClass() @GetItemClass(s)">
    <div class="server-name">
        @s.IconSpan()
        <a href="@Url.Action(nameof(DashboardController.Node), "Dashboard", new { node = s.PrettyName })">@s.PrettyName</a>
        @if (s.IsUnwatched)
        {
            <span class="unmanaged">(unmanaged)</span>
        }
        <span class="category">@s.Category.Name</span>
    </div>
    <div class="status-block cpu-status">
        <span class="label">CPU </span>@s.CPUStatusSpan() 
        <div class="status-graph">@Graph(s, "CPU")</div>
    </div>
    <div class="status-block mem-status">
        <span class="label">Mem </span>@s.MemoryPercentStatusSpan()
        <div class="status-graph">@s.MemoryStatusSpan()@if (s.HasValidMemoryReading) {
            <div class="space-used" style="width: 215px;"><div class="used @s.MemoryMonitorStatus().AsString(EnumFormat.Description)" style="width: @(s.PercentMemoryUsed?.ToString(CultureInfo.InvariantCulture))%"></div></div>
        }
        </div>
    </div>
    <div class="status-block net-status">
        <span class="label">Net </span>@s.PrettyTotalNetwork() 
        <div class="status-graph">@Graph(s, "Network")</div>
    </div>
</div>

src/Opserver.Web/Views/Hub/Index.Dashboard.cshtml
@using Opserver.Data.Dashboard
@inject DashboardModule Dashboard
@{
    var nodes = Dashboard.AllNodes;
    var groups = nodes.GroupBy(n => n.Category).OrderBy(g => g.Key.Index).ToList();
}
<div class="panel panel-default">
    <div class="panel-heading">@nodes.GetWorstStatus().IconSpan() @nodes.Count.Pluralize("Node")</div>
    <div class="panel-body">
        <table class="table table-super-condensed table-striped col-md-12">
            <tbody>
                <tr>
                    <th>Group</th>
                    <th>Nodes</th>
                    <th>Network</th>
                </tr>
                @foreach (var g in groups)
                {
                    <tr>
                        <td>@g.Key.Name</td>
                        <td>@Health.Description(g)</td>
                        <td>@g.Sum(n => n.TotalPrimaryNetworkBitsPerSecond < 0 ? 0 : n.TotalPrimaryNetworkBitsPerSecond).ToSpeed()</td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr class="total-row">
                    <td><strong>Total</strong></td>
                    <td>@Health.Description(nodes)</td>
                    <td>@nodes.Sum(n => n.TotalPrimaryNetworkBitsPerSecond < 0 ? 0 : n.TotalPrimaryNetworkBitsPerSecond).ToSpeed()</td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

src/Opserver.Web/Views/Hub/Index.Elastic.cshtml
@using Opserver.Data.Elastic
@using Opserver.Views.Shared.Guages
@inject ElasticModule Module
@{
    var all = Module.Clusters;
}
<div class="panel panel-default">
    <div class="panel-heading">@all.GetWorstStatus().IconSpan() Elasticsearch</div>
    <div class="panel-body">
        <div class="col-xs-4">
            <partial Name="Gauges/Circle" Model="@(new CircleModel("Cluster", all))" />
        </div>
        <div class="col-xs-4">
            <partial Name="Gauges/Circle" Model="@(new CircleModel("Index", all.SelectMany(c => c.HealthStatus.Data?.Indexes?.Values ?? Enumerable.Empty<ElasticCluster.ClusterHealthInfo.IndexHealthInfo>())))" />
        </div>
        <div class="col-xs-4">
            <partial Name="Gauges/Circle" Model="@(new CircleModel("Shard", all.SelectMany(c => c.AllShards)))" />
        </div>

        <table class="table table-super-condensed table-striped col-md-12">
            <tbody>
                <tr>
                    <th>Cluster</th>
                    <th>CPU</th>
                    <th>Mem</th>
                    <th>Indexes</th>
                    <th>Shards</th>
                    <th>Searches</th>
                </tr>
                @foreach (var c in all)
                {
                    var cShards = c.AllShards;
                    var indexes = c.HealthStatus.Data?.Indexes?.Values;
                    var master = c.MasterNode;
                    <tr>
                        <td>
                            @c.IconSpan() <a href="@Url.Action(nameof(ElasticController.Cluster), "Elastic", new { cluster = c.Name})">@c.Name</a>
                            @if (master != null)
                            {
                                <div><label>M:</label> @master.IconSpan() @c.ShortName(master)</div>
                            }
                        </td>
                        <td>@(c.Nodes.Data?.Nodes?.Sum(n => n.Stats?.Process?.CPU?.Percent).ToComma())%</td>
                        <td>@(c.Nodes.Data?.Nodes?.Sum(n => n.Stats?.Process?.Memory?.ResidentInBytes)?.ToSize())</td>
                        <td>@indexes.GetWorstStatus().IconSpan() @(indexes?.Count.ToComma())</td>
                        <td>@cShards.Count.ToComma() <span class="text-muted small">(@cShards.Count(s => s.Primary).ToComma())</span></td>
                        <td>@(c.Nodes.Data?.Nodes?.Sum(n => n.Stats?.Indexes?.Search?.QueryTotal).ToComma())</td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr class="total-row">
                    <td><strong>Total</strong></td>
                    <td></td>
                    <td></td>
                    <td>@all.Sum(c => c.HealthStatus.Data?.Indexes?.Values.Count ?? 0).ToComma()</td>
                    <td>@all.Sum(c => c.AllShards.Count).ToComma()</td>
                    <td>@all.Sum(c => c.Nodes.Data?.Nodes?.Sum(n => n.Stats?.Indexes?.Search?.QueryTotal)).ToComma()</td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

src/Opserver.Web/Views/Hub/Index.HAProxy.cshtml
@using Opserver.Data.HAProxy
@using Opserver.Views.Shared.Guages
@inject HAProxyModule HAProxy
@{
    var allGroups = HAProxy.Groups;
    var allProxies = HAProxy.GetAllProxies();
    var allServers = allProxies.SelectMany(p => p.Servers).ToList();
    var totalUp = allServers.Count(s => s.MonitorStatus == MonitorStatus.Good);
    var totalOut = allServers.Count(s => s.OutOfRotation);
    var totalDown = allServers.Count(s => s.MonitorStatus != MonitorStatus.Good && !s.OutOfRotation);
}
<div class="panel panel-default">
    <div class="panel-heading">@allGroups.GetWorstStatus().IconSpan() HAProxy</div>
    <div class="panel-body">
        <div class="col-xs-4">
            <partial Name="Gauges/Circle" Model="@(new CircleModel("Group", allGroups))" />
        </div>
        <div class="col-xs-4">
            <partial Name="Gauges/Circle" Model="@(new CircleModel("Proxy", allProxies))" />
        </div>
        <div class="col-xs-4">
            <partial Name="Gauges/Circle" Model="@(new CircleModel("Server", allServers))" />
        </div>
        <table class="table table-super-condensed table-striped col-md-12">
            <thead>
                <tr>
                    <th>Group</th>
                    <th>In</th>
                    <th>Out</th>
                    <th>Down</th>
                    <th>Sessions</th>
                    <th>Rate</th>
                </tr>
            </thead>
            <tbody>
            @foreach (var group in allGroups)
            {
                var servers = group.GetProxies().SelectMany(p => p.Servers).ToList();
                var gOut = servers.Count(s => s.OutOfRotation);
                var gDown = servers.Count(s => s.MonitorStatus != MonitorStatus.Good && !s.InMaintenance);
                <tr>
                    <td>@group.IconSpan() @group.Name</td>
                    <td>@servers.Count(s => s.MonitorStatus == MonitorStatus.Good).ToComma()</td>
                    <td class="@(gOut > 0 ? MonitorStatus.Maintenance.TextClass() : null)">@gOut.ToComma()</td>
                    <td class="@(gDown > 0 ? MonitorStatus.Critical.TextClass() : null)">@gDown.ToComma()</td>
                    <td>@servers.Sum(s => s.CurrentSessions).ToComma()</td>
                    <td>@servers.Sum(s => s.CurrentNewSessionsPerSecond).ToComma()</td>
                </tr>
            }
            </tbody>
            <tfoot>
                <tr class="total-row">
                    <td><strong>Total</strong></td>
                    <td>@totalUp.ToComma()</td>
                    <td class="@(totalOut > 0 ? MonitorStatus.Maintenance.TextClass() : null)">@totalOut.ToComma()</td>
                    <td class="@(totalDown > 0 ? MonitorStatus.Critical.TextClass() : null)">@totalDown.ToComma()</td>
                    <td>@allServers.Sum(s => s.CurrentSessions).ToComma()</td>
                    <td>@allServers.Sum(s => s.CurrentNewSessionsPerSecond).ToComma()</td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

src/Opserver.Web/Views/Hub/Index.Issues.cshtml
@inject PollingService Poller
@{
    var issues = Poller.GetIssues().OrderByWorst().ToList();
}
<div class="panel panel-default">
    <div class="panel-heading">@((issues.Count > 0 ? MonitorStatus.Warning : MonitorStatus.Good).IconSpan()) @issues.Count.Pluralize("Issue")</div>
    <div class="panel-body">
        @foreach (var i in issues)
        {
            <div>
                <h6>
                    @i.MonitorStatus.IconSpan() @i.Title <span class="text-muted">(@(i.Type ?? "Unknown Type"))</span>
                    <span class="pull-right small">@i.Date.ToRelativeTimeSpan()</span>
                </h6>
                <div>@i.Description</div>
                <p></p>
            </div>
        }
    </div>
</div>

src/Opserver.Web/Views/Hub/Index.SQL.cshtml
@using Opserver.Data.SQL
@using Opserver.Views.Shared.Guages
@inject SQLModule Sql
@{
    var all = Sql.AllInstances;
}
<div class="panel panel-default">
    <div class="panel-heading">@all.GetWorstStatus().IconSpan() SQL</div>
    <div class="panel-body">
        <div class="col-xs-4">
            <partial Name="Gauges/Circle" Model="@(new CircleModel("Instance", all))" />
        </div>
        <div class="col-xs-4">
            <partial Name="Gauges/Circle" Model="@(new CircleModel("AG", Sql.Clusters.SelectMany(c => c.AvailabilityGroups)))" />
        </div>
        <div class="col-xs-4">
            <partial Name="Gauges/Circle" Model="@(new CircleModel("Database", all.SelectMany(i => i.Databases.SafeData(true))))" />
        </div>
        <table class="table table-super-condensed table-striped col-md-12">
            @foreach (var c in Sql.Clusters)
            {
                <tbody>
                <tr>
                    <th>@c.Name</th>
                    <th>CPU</th>
                    <th>Mem</th>
                    <th>DBs</th>
                    <th>Batches</th>
                </tr>
                @foreach (var i in c.Nodes)
                {
                    <tr class="@i.RowClass()@(i.IsAllAGsPrimary ? " info" : null)">
                        <td>@i.IconSpan() <a href="~/sql/instance?node=@i.Name.UrlEncode()">@i.Name</a></td>
                        <td><img src="~/graph/sql/cpu/spark?node=@i.Name&time=@DateTime.UtcNow.ToString("yyyy-MM-dd")" width="100" height="16"/></td>
                        <partial Name="Partials.MemoryCell" Model="new PartialsMemoryCellModel(i)" />
                        <td>@Health.Description(i.Databases.SafeData(true))</td>
                        <td>@(i.BatchesPerSec?.ToComma())</td>
                    </tr>
                }
                </tbody>
            }
            <tbody>
            <tr>
                <th>Standalone</th>
                <th>CPU</th>
                <th>Mem</th>
                <th>DBs</th>
                <th>Batches</th>
            </tr>
            @foreach (var i in Sql.StandaloneInstances)
            {
                <tr class="@i.RowClass()">
                    <td>@i.IconSpan() <a href="~/sql/instance?node=@i.Name.UrlEncode()">@i.Name</a></td>
                    <td><img src="~/graph/sql/cpu/spark?node=@i.Name&time=@DateTime.UtcNow.ToString("yyyy-MM-dd")" width="100" height="16"/></td>
                    <partial Name="Partials.MemoryCell" Model="new PartialsMemoryCellModel(i)" />
                    <td>@Health.Description(i.Databases.SafeData(true))</td>
                    <td>@(i.BatchesPerSec?.ToComma())</td>
                </tr>
            }
            </tbody>
            <tfoot>
                <tr class="total-row">
                    <td><strong>Total</strong></td>
                    <td></td>
                    <td></td>
                    <td>@all.Sum(i => i.Databases.Data?.Count ?? 0).ToComma()</td>
                    <td>@all.Sum(i => i.BatchesPerSec ?? 0).ToComma()</td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

src/Opserver.Web/Views/Hub/Index.cshtml
@using Opserver.Views.Hub
@inject Opserver.Data.Dashboard.DashboardModule Dashboard
@inject Opserver.Data.SQL.SQLModule Sql
@inject Opserver.Data.Elastic.ElasticModule Elastic
@inject Opserver.Data.HAProxy.HAProxyModule HAProxy
@model HubModel
@{
    this.SetPageTitle("Hub");

    // Just making this compile and run for now
    // TODO: Move to registration elsewhere, or maybe we look for Hub.cshtml (or something) in those view folders
    // Ideally, the data layer doesn't know about view names
    var views = new List<string>();
    if (Dashboard.Enabled)
    {
        views.Add("Index.Dashboard");
    }
    if (Sql.Enabled)
    {
        views.Add("Index.SQL");
    }
    if (Elastic.Enabled)
    {
        views.Add("Index.Elastic");
    }
    if (HAProxy.Enabled)
    {
        views.Add("Index.HAProxy");
    }
}
@section head {
    <script>
        $(function() {
            Status.Dashboard.init({ refresh: 60 });
        });
    </script>
}
<div>
    <div class="small js-refresh" data-name="all-servers">
        <div class="col-md-4">
            @for (var i = 0; i < views.Count; i += 2)
            {
                <partial name="@views[i]" />
            }
        </div>
        <div class="col-md-4">
            @for (var i = 1; i < views.Count; i += 2)
            {
                <partial name="@views[i]" />
            }
        </div>
        <div class="col-md-4">
            <partial name="Index.Issues" />
        </div>
    </div>
</div>

src/Opserver.Web/Views/Hub/SQL.AvailabilityGroup.cshtml
@model Opserver.Data.SQL.SQLNode.AGInfo
<div class="item availability-group">
    <partial name="~/Views/SQL/Servers.AvailabilityGroup.cshtml" model="Model" />
</div>