src/Opserver.Web/Controllers/ElasticController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Opserver.Data.Elastic;
using Opserver.Helpers;
using Opserver.Views.Elastic;

namespace Opserver.Controllers
{
    [OnlyAllow(ElasticRoles.Viewer)]
    public class ElasticController : StatusController<ElasticModule>
    {
        public ElasticController(ElasticModule module, IOptions<OpserverSettings> settings) : base(module, settings) { }

        [DefaultRoute("elastic")]
        public ActionResult Dashboard()
        {
            var vd = new DashboardModel
            {
                Clusters = Module.Clusters,
                View = DashboardModel.Views.AllClusters,
                DisplayMode = DashboardModel.DisplayModes.InterestingOnly
            };
            return View("AllClusters", vd);
        }

        [Route("elastic/cluster")]
        public ActionResult Cluster(string cluster, string node)
        {
            var vd = GetViewData(cluster, node);
            vd.View = DashboardModel.Views.Cluster;
            return View("Cluster", vd);
        }

        [Route("elastic/node")]
        public ActionResult Node(string cluster, string node)
        {
            var vd = GetViewData(cluster, node);
            vd.View = DashboardModel.Views.Node;
            return View("Node", vd);
        }

        [Route("elastic/node/modal/{type}")]
        public ActionResult NodeModal(string cluster, string node, string type)
        {
            var vd = GetViewData(cluster, node);
            return type switch
            {
                "settings" => PartialView("Node.Settings", vd),
                _ => ContentNotFound("Unknown modal view requested"),
            };
        }

        [Route("elastic/cluster/modal/{type}")]
        public ActionResult ClusterModal(string cluster, string node, string type)
        {
            var vd = GetViewData(cluster, node);
            return type switch
            {
                "indexes" => PartialView("Cluster.Indexes", vd),
                _ => ContentNotFound("Unknown modal view requested"),
            };
        }

        [Route("elastic/index/modal/{type}")]
        public ActionResult IndexModal(string cluster, string node, string index, string type)
        {
            var vd = GetViewData(cluster, node, index);
            return type switch
            {
                "shards" => PartialView("Cluster.Shards", vd),
                _ => ContentNotFound("Unknown modal view requested"),
            };
        }

        private DashboardModel GetViewData(string cluster, string node = null, string index = null)
        {
            // Cluster names are not unique, names + node names should be though
            // If we see too many people with crazy combos, then node GUIDs it is.
            var cc = Module.Clusters.Find(
                c => string.Equals(c.Name, cluster, StringComparison.InvariantCultureIgnoreCase)
                  && (node.IsNullOrEmpty() || (c.Nodes.Data?.Get(node) != null)));
            var cn = cc?.Nodes.Data.Get(node);

            return new DashboardModel
            {
                Clusters = Module.Clusters,
                CurrentNodeName = node,
                CurrentClusterName = cc?.Name,
                CurrentIndexName = index,
                CurrentCluster = cc,
                CurrentNode = cn
            };
        }

        [Route("elastic/indexes")]
        public ActionResult Indexes(string cluster, string node, string guid)
        {
            var vd = GetViewData(cluster, node ?? guid);
            vd.View = DashboardModel.Views.Indexes;
            return View("Indexes", vd);
        }

        [Route("elastic/reroute/{type}")]
        public ActionResult Reroute(string type) //, string index, int shard, string node)
        {
            bool result = false;
            switch (type)
            {
                case "assign":
                    result = true;
                    break;
                case "cancel":
                    result = true;
                    break;
            }
            return Json(result);
        }
    }
}

src/Opserver.Web/Controllers/RedisController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Opserver.Data.Redis;
using Opserver.Helpers;
using Opserver.Views.Redis;

namespace Opserver.Controllers
{
    [OnlyAllow(RedisRoles.Viewer)]
    public partial class RedisController : StatusController<RedisModule>
    {
        public RedisController(RedisModule module, IOptions<OpserverSettings> settings) : base(module, settings) { }

        [DefaultRoute("redis")]
        public ActionResult Dashboard(string node)
        {
            var instances = Module.GetAllInstances(node);
            if (instances.Count == 1 && instances[0] != null)
            {
                // In the 1 case, redirect
                return RedirectToAction(nameof(Instance), new { node });
            }
            var vd = new DashboardModel
            {
                ReplicationGroups = Module.ReplicationGroups,
                Instances = instances.Count > 1 ? instances : Module.Instances,
                View = node.HasValue() ? RedisViews.Server : RedisViews.All,
                CurrentRedisServer = node,
                Refresh = true
            };
            return View("Dashboard.Instances", vd);
        }

        [Route("redis/instance")]
        public ActionResult Instance(string node)
        {
            var instance = Module.GetInstance(node);

            var vd = new DashboardModel
            {
                Instances = Module.Instances,
                CurrentInstance = instance,
                View = RedisViews.Instance,
                CurrentRedisServer = node,
                Refresh = true
            };
            return View(vd);
        }

        [Route("redis/instance/get-config/{host}-{port}-config.zip")]
        public ActionResult DownloadConfiguration(string host, int port)
        {
            var instance = Module.GetInstance(host, port);
            var configZip = instance.GetConfigZip();
            return new FileContentResult(configZip, "application/zip");
        }

        [Route("redis/instance/summary/{type}")]
        public ActionResult InstanceSummary(string node, string type)
        {
            var i = Module.GetInstance(node);
            if (i == null) return ContentNotFound("Could not find instance " + node);

            return type switch
            {
                "config" => PartialView("Instance.Config", i),
                "clients" => PartialView("Instance.Clients", i),
                "info" => PartialView("Instance.Info", i),
                "slow-log" => PartialView("Instance.SlowLog", i),
                _ => ContentNotFound("Unknown summary view requested"),
            };
        }

        [Route("redis/analyze/memory")]
        public ActionResult Analysis(string node, int db, bool runOnMaster = false)
        {
            var instance = Module.GetInstance(node);
            if (instance == null)
                return TextPlain("Instance not found");
            var analysis = instance.GetDatabaseMemoryAnalysis(db, runOnMaster);

            return View("Instance.Analysis.Memory", analysis);
        }

        [Route("redis/analyze/memory/clear")]
        public ActionResult ClearAnalysis(string node, int db)
        {
            var instance = Module.GetInstance(node);
            if (instance == null)
                return TextPlain("Instance not found");
            instance.ClearDatabaseMemoryAnalysisCache(db);

            return RedirectToAction(nameof(Analysis), new { node, db });
        }
    }
}

src/Opserver.Web/Controllers/SQLController.cs
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Options;
using Opserver.Data.SQL;
using Opserver.Helpers;
using Opserver.Views.SQL;

namespace Opserver.Controllers
{
    [OnlyAllow(SQLRoles.Viewer)]
    public partial class SQLController : StatusController<SQLModule>
    {
        public SQLController(SQLModule sqlModule, IOptions<OpserverSettings> settings) : base(sqlModule, settings) { }

        [DefaultRoute("sql")]
        public ActionResult Dashboard() => RedirectToAction(nameof(Servers));

        [Route("sql/servers")]
        public ActionResult Servers(string cluster, string node, string ag, bool detailOnly = false)
        {
            var vd = new ServersModel
                {
                    AzureServers = Module.AzureServers,
                    StandaloneInstances = Module.StandaloneInstances,
                    Clusters = Module.Clusters,
                    Refresh = node.HasValue() ? 10 : 5
                };


            if (cluster.HasValue())
                vd.CurrentCluster = vd.Clusters.Find(c => string.Equals(c.Name, cluster, StringComparison.OrdinalIgnoreCase));
            if (vd.CurrentCluster != null)
                vd.AvailabilityGroups = vd.CurrentCluster.GetAvailabilityGroups(node, ag).ToList();

            if (detailOnly && vd.CurrentCluster != null)
                return PartialView("Servers.ClusterDetail", vd);

            return View("Servers", vd);
        }

        [Route("sql/jobs")]
        public ActionResult AllJobs(JobSort? sort = null, SortDir? dir = null)
        {
            var vd = new ServersModel
            {
                View = SQLViews.Jobs,
                AzureServers = Module.AzureServers,
                StandaloneInstances = Module.StandaloneInstances,
                Clusters = Module.Clusters,
                Refresh = 30,
                JobSort = sort,
                SortDirection = dir
            };

            return View("AllJobs", vd);
        }

        [Route("sql/instance")]
        public ActionResult Instance(string node)
        {
            var i = Module.GetInstance(node);
            var vd = new InstanceModel
            {
                View = SQLViews.Instance,
                Refresh = node.HasValue() ? 10 : 5,
                CurrentInstance = i
            };
            return View("Instance", vd);
        }

        [Route("sql/instance/summary/{type}")]
        public ActionResult InstanceSummary(string node, string type)
        {
            var i = Module.GetInstance(node);
            if (i == null) return NoInstanceRedirect(node);

            return type switch
            {
                "configuration" => PartialView("Instance.Configuration", i),
                "connections" => PartialView("Instance.Connections", i),
                "errors" => PartialView("Instance.Errors", i),
                "memory" => PartialView("Instance.Memory", i),
                "jobs" => PartialView("Instance.Jobs", i),
                "db-files" => PartialView("Instance.DBFiles", i),
                _ => ContentNotFound("Unknown summary view requested"),
            };
        }

        [ResponseCache(Duration = 5 * 1, VaryByQueryKeys = new string[] { "node", "sort", "options" }, Location = ResponseCacheLocation.Client)]
        [Route("sql/top")]
        public ActionResult Top(string node, SQLInstance.TopSearchOptions options)
        {
            var vd = GetOperationsModel(node, options);
            var i = vd.CurrentInstance;

            if (i != null)
            {
                var cache = i.GetTopOperations(options);
                vd.TopOperations = cache.Data;
                vd.ErrorMessage = cache.ErrorMessage;
            }

            return View("Operations.Top", vd);
        }

        [Route("sql/top/filters")]
        public ActionResult TopFilters(string node, SQLInstance.TopSearchOptions options) =>
            View("Operations.Top.Filters", GetOperationsModel(node, options));

        private OperationsTopModel GetOperationsModel(string node, SQLInstance.TopSearchOptions options)
        {
            var i = Module.GetInstance(node);
            options.SetDefaults();

            return new OperationsTopModel
            {
                View = SQLViews.Top,
                CurrentInstance = i,
                TopSearchOptions = options
            };
        }

        [Route("sql/top/detail")]
        public ActionResult TopDetail(string node, string handle, int? offset = null)
        {
            var planHandle = WebEncoders.Base64UrlDecode(handle);

            var i = Module.GetInstance(node);

            var vd = new OperationsTopDetailModel
            {
                Instance = i,
                Op = i.GetTopOperation(planHandle, offset).Data
            };
            return PartialView("Operations.Top.Detail", vd);
        }

        [Route("sql/top/plan")]
        public ActionResult TopPlan(string node, string handle)
        {
            var planHandle = WebEncoders.Base64UrlDecode(handle);
            var i = Module.GetInstance(node);
            var op = i.GetTopOperation(planHandle).Data;
            if (op == null) return ContentNotFound("Plan was not found.");

            var ms = new MemoryStream(Encoding.UTF8.GetBytes(op.QueryPlan));

            return File(ms, "text/xml", $"QueryPlan-{Math.Abs(handle.GetHashCode())}.sqlplan");
        }

        [Route("sql/active")]
        public ActionResult Active(string node, SQLInstance.ActiveSearchOptions options) =>
            View("Operations.Active", GetOperationsActiveModel(node, options));

        [Route("sql/active/filters")]
        public ActionResult ActiveFilters(string node, SQLInstance.ActiveSearchOptions options) =>
            View("Operations.Active.Filters", GetOperationsActiveModel(node, options));

        private OperationsActiveModel GetOperationsActiveModel(string node, SQLInstance.ActiveSearchOptions options)
        {
            var i = Module.GetInstance(node);
            return new OperationsActiveModel
            {
                View = SQLViews.Active,
                CurrentInstance = i,
                ActiveSearchOptions = options
            };
        }

        [Route("sql/connections")]
        public async Task<ActionResult> Connections(string node)
        {
            var i = Module.GetInstance(node);
            var vd = new DashboardModel
            {
                View = SQLViews.Connections,
                CurrentInstance = i,
                Cache = i?.Connections,
                Connections = i == null ? null : await i.Connections.GetData()
            };
            return View(vd);
        }

        [Route("sql/databases")]
        public ActionResult Databases(string node)
        {
            var i = Module.GetInstance(node);
            var vd = new DashboardModel
            {
                View = SQLViews.Databases,
                CurrentInstance = i,
                Refresh = 2*60
            };
            return View(vd);
        }

        [Route("sql/db/{database}/{view}")]
        [Route("sql/db/{database}/{view}/{objectName}")]
        public ActionResult DatabaseDetail(string node, string database, string view, string objectName)
        {
            var i = Module.GetInstance(node);
            var vd = new DatabasesModel
            {
                Instance = i,
                Database = database,
                ObjectName = objectName
            };
            switch (view)
            {
                case "backups":
                    vd.View = DatabasesModel.Views.Backups;
                    return View("Databases.Modal.Backups", vd);
                case "restores":
                    vd.View = DatabasesModel.Views.Restores;
                    return View("Databases.Modal.Restores", vd);
                case "storage":
                    vd.View = DatabasesModel.Views.Storage;
                    return View("Databases.Modal.Storage", vd);
                case "tables":
                    vd.View = DatabasesModel.Views.Tables;
                    return View("Databases.Modal.Tables", vd);
                case "views":
                    vd.View = DatabasesModel.Views.Views;
                    return View("Databases.Modal.Views", vd);
                case "unusedindexes":
                    vd.View = DatabasesModel.Views.UnusedIndexes;
                    return View("Databases.Modal.UnusedIndexes", vd);
                case "missingindexes":
                    vd.View = DatabasesModel.Views.MissingIndexes;
                    return View("Databases.Modal.MissingIndexes", vd);
                case "storedprocedures":
                    vd.View = DatabasesModel.Views.StoredProcedures;
                    return View("Databases.Modal.StoredProcedures", vd);
            }
            return View("Databases.Modal.Tables", vd);
        }

        [Route("sql/databases/tables")]
        public ActionResult DatabaseTables(string node, string database)
        {
            var i = Module.GetInstance(node);
            var vd = new DatabasesModel
            {
                Instance = i,
                Database = database
            };
            return View("Databases.Modal.Tables", vd);
        }

        private ActionResult NoInstanceRedirect(string node) =>
            Request.IsAjax()
            ? ContentNotFound("Instance " + node + " was not found.")
            : (ActionResult)View("Instance.Selector", new DashboardModel());
    }
}

src/Opserver.Web/Views/Shared/AccessDenied.cshtml
@{
    this.SetPageTitle("Access Denied");
}
<div class="row">
    <div class="col-md-6 col-md-offset-3 text-center" style="margin-top: 100px">
        <h2>
            <i class="fa fa-lock text-danger" aria-hidden="true"></i> Access Denied
        </h2>
        <p>
            You do not have permissions to see this page.
        </p>
    </div>
</div>

src/Opserver.Web/Views/Shared/Guages.Circle.cshtml
@using System.Globalization
@using Opserver
@using Opserver.Data
@model (string Label, IEnumerable<IMonitorStatus> Items)
@{
    const double Full = 45 * 2 * Math.PI;
    string FullStr = Full.ToString(CultureInfo.InvariantCulture);
    var statuses = Model.Items.OrderBy(i => i.MonitorStatus).ToList().GroupBy(i => i.MonitorStatus).ToList();
    var worst = MonitorStatus.Good;
    var total = statuses.Sum(i => i.Count());
    double startDeg = 0;
}
<div class="circle-percent">
    <svg viewBox="0 0 100 100">
        <circle r="45" cx="50" cy="50" stroke-dasharray="@Full.ToString(CultureInfo.InvariantCulture)" stroke-dashoffset="0" />
        @foreach (var s in statuses)
        {
            if (s.Key > worst)
            {
                worst = s.Key;
            }
            var percent = s.Count()/(double) total;
            var deg = percent*360;
            <circle class="stroke-@s.Key.RawClass(true, true)@(s.Key != MonitorStatus.Good ? " filled" : null)" r="45" cx="50" cy="50"
                    stroke-dasharray="@FullStr" 
                    style="stroke-dashoffset: @((Full-percent*Full).ToString(CultureInfo.InvariantCulture)); transform: rotate(@(startDeg.ToString(CultureInfo.InvariantCulture))deg);" />
            startDeg += deg;
        }
        @if (!statuses.Any())
        {
            <circle class="stroke-@(MonitorStatus.Unknown.RawClass())" r="45" cx="50" cy="50" stroke-dasharray="@Full.ToString(CultureInfo.InvariantCulture)" stroke-dashoffset="0" />
        }
    </svg>
    <div class="circle-label"><span>@total.ToComma()</span><p>@total.Pluralize(Model.Label, false)</p></div>
</div>

src/Opserver.Web/Views/Shared/Issues.cshtml
@inject PollingService Poller
@using Opserver.Data.Dashboard
@using Opserver.Data.Elastic
@using Opserver.Data.HAProxy
@using Opserver.Data.Redis
@using Opserver.Data.SQL
@{
    var issues = Poller.GetIssues();
}
@functions
{
    public string GetLink(Issue i)
    {
        var node = i as Issue<Node>;
        if (node?.Item != null)
        {
            return Url.Action(nameof(DashboardController.Node), "Dashboard", new { node = node.Item.PrettyName });
        }
        var agIssue = i as Issue<SQLNode.AGInfo>;
        if (agIssue?.Item != null)
        {
            return $"/sql/servers#/cluster/{agIssue.Item.ClusterName.UrlEncode()}/{agIssue.Item.Name.UrlEncode()}";
        }
        var sqlInstance = i as Issue<SQLInstance>;
        if (sqlInstance?.Item != null)
        {
            return Url.Action(nameof(SQLController.Instance), "SQL", new { node = sqlInstance.Item.Name });
        }
        var redisInstance = i as Issue<RedisInstance>;
        if (redisInstance?.Item != null)
        {
            return Url.Action(nameof(RedisController.Instance), "Redis", new { node = redisInstance.Item.HostAndPort });
        }
        var elasticCluster = i as Issue<ElasticCluster>;
        if (elasticCluster?.Item != null)
        {
            return Url.Action(nameof(ElasticController.Cluster), "Elastic", new { cluster = elasticCluster.Item.Name });
        }
        var haproxyGroup = i as Issue<HAProxyGroup>;
        if (haproxyGroup?.Item != null)
        {
            return Url.Action(nameof(HAProxyController.Dashboard), "HAProxy", new { group = haproxyGroup.Item.Name });
        }
        return string.Empty;
    }
}
<h4 class="modal-title">
    @issues.Count.Pluralize("Active Issue")
</h4>
@if (issues.Any())
{
    <div class="list-group list-group-sm">
        @foreach (var i in issues)
        {
            <a href="@GetLink(i)" class="list-group-item @i.MonitorStatus.BackgroundClass()">
                <h6 class="list-group-item-heading">
                    @i.MonitorStatus.IconSpan() @i.Title <span class="text-muted">(@(i.Type ?? "Unknown Type"))</span>
                    <span class="pull-right small">@i.Date.ToRelativeTimeSpan()</span>
                </h6>
                <p class="list-group-item-text">@i.Description</p>
            </a>
        }
    </div>
}
else
{
    <div class="text-muted">No current issues found.</div>
}

src/Opserver.Web/Views/Shared/IssuesButton.cshtml
@inject PollingService Poller
@{
    var issues = Poller.GetIssues();
}
@if (issues.Any())
{
    <ul class="nav navbar-nav">
        <li>
            <a href="#/issues" class="js-issues-botton" data-count="@issues.Count.ToString()"><span class="badge alert-@issues.GetWorstStatus().RawClass()">@issues.Count.ToComma()</span></a>
        </li>
    </ul>
}

src/Opserver.Web/Views/Shared/Master.cshtml
@using Opserver.Views.Shared
@using StackExchange.Profiling
@inject IJsonHelper Json
@{
    var topNodes = ViewData[ViewDataKeys.TopBoxOptions] as TopBoxOptions;
    var baseTitle = ViewData[ViewDataKeys.PageTitle] as string;
    var title = baseTitle.HasValue() ? Settings.Global.SiteName + " - " + baseTitle : Settings.Global.SiteName;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@title</title>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="google" value="notranslate" />
    @RenderSection("preload", false)
    <link href="~/Content/themes/@(Current.Theme).min.css" asp-append-version="true" rel="stylesheet" />
    <link href="~/Content/img/apple-touch-icon.png" asp-append-version="true" rel="apple-touch-icon" />
    <script src="~/Content/js/jquery-2.2.4.min.js" asp-append-version="true"></script>
    <script src="~/Content/js/bundle.min.js" asp-append-version="true"></script>
    <script>
        $(function() {
            Status.init({ SiteName: '@Settings.Global.SiteName', Tab:'@Current.NavTab?.Name', rootPath: '@Url.Content("~/")', HeaderRefresh: 15 });
            @if (topNodes?.AllNodes?.Any() ?? false)
            {
                var serverJson = topNodes.AllNodes.Select(n => new
                    {
                        label = n.DisplayName,
                        value = n.Name,
                        icon = n.MonitorStatus.TextClass(showGood: true),
                        category = n.CategoryName
                    }).OrderBy(n => n.category).ThenBy(n => n.label);
                @:Status.NodeSearch.init({ nodes: @Json.Serialize(serverJson) });
            }
        });
    </script>    @RenderSection("head", false)    @MiniProfiler.Current.RenderIncludes(Context)
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="~/hub" aria-label="Status Hub"></a>
            </div>

            <div class="collapse navbar-collapse" id="topbar-collapse">
                <partial name="IssuesButton" />
                @if (topNodes?.SearchOnly ?? false)
                {
                    <form action="@topNodes.Url" method="GET" class="navbar-form navbar-left" role="search">
                        <div class="form-group-sm">
                            <input type="text" class="form-control js-filter" placeholder="Search@(topNodes.SearchText.HasValue() ? " " + topNodes.SearchText : "")..." value="@topNodes.SearchValue" name="@topNodes.QueryParam" />
                        </div>
                        @if (topNodes.SearchParams != null)
                        {
                            foreach (var p in topNodes.SearchParams)
                            {
                                <input type="hidden" name="@p.Key" value="@p.Value" />
                            }
                        }
                    </form>
                }
                else if (topNodes?.AllNodes?.Any() ?? false)
                {
                    var s = topNodes.CurrentNode;
                    <form action="@topNodes.Url" method="GET" class="navbar-form navbar-left" role="search">
                        <div class="form-group-sm">
                            <input type="text" class="form-control js-filter@(s != null ? " left-icon " + s.MonitorStatus.TextClass() : "")" placeholder="Search@(topNodes.SearchText.HasValue() ? " " + topNodes.SearchText : "")..." value="@(s?.DisplayName)" name="node" />
                        </div>
                    </form>
                }
                <partial name="TopTabs" />
            </div>
        </div>
    </nav>
    <div class="container-fluid js-content">
        @RenderBody()
    </div>
</body>
</html>

src/Opserver.Web/Views/Shared/NoConfiguration.cshtml
@{
    this.SetPageTitle("No configuration");
}
<div class="row">
    <div class="col-xs-10 col-xs-offset-1" style="margin-top: 100px">
        <h2 class="text-center">
            <i class="fa fa-exclamation-triangle text-warning" aria-hidden="true"></i> Uh no! Configuration Problem!
        </h2>
        @if (!Current.Security.IsConfigured)
        {
            <p>
                No security provider was found! This means the security section in your config is either missing or has an invalid provider.
            </p>
            <p>See the configuration docs here: <a href="#">TODO: Fix after merge</a></p>
        }
        else
        {
            <p>
                No configuration data was found. This means no Opserver sections are configured/enabled or you have no roles assigned to you.
            </p>
            <p>
                See the <code>Readme.txt</code> in /Config and <code>*.example.json</code> files for examples of a basic JSON configuration...or you can implement your own provider to get settings from anywhere.
            </p>
            <p>
                You can browse to <a href="~/about">/about</a> to see how you have been authenticated and what monitors have been enabled.
            </p>    
        }
    </div>
</div>

src/Opserver.Web/Views/Shared/PageNotFound.cshtml
@model Opserver.Views.Shared.PageNotFoundModel
@{
    this.SetPageTitle("404 - Not Found");
}
<div class="row">
    <div class="col-md-6 col-md-offset-3 text-center" style="margin-top: 100px">
        <h2>
            <i class="fa fa-exclamation-triangle text-info" aria-hidden="true"></i> @Model.Title.IsNullOrEmptyReturn("404 - Not Found")
        </h2>
        <p>
            @Model.Message.IsNullOrEmptyReturn("The page you were looking for could not be found.")
        </p>
    </div>
</div>

src/Opserver.Web/Views/Shared/Partials.MemoryCell.cshtml
@inject Opserver.Data.Dashboard.DashboardModule Dashboard
@model PartialsMemoryCellModel
@{ 
    var i = Model.Instance;
    var serverInfo = Dashboard.GetNodeByName(i.Name);
}
@if (serverInfo != null)
{
    <td>@(serverInfo?.MemoryPercentStatusSpan())</td>
}
else
{
    var props = i.ServerProperties.SafeData();
    if (props != null && props.PhysicalMemoryBytes > 0)
    {
        <td title="@props.CommittedBytes.ToSize() / @props.PhysicalMemoryBytes.ToSize()">@(decimal.Round(i.CurrentMemoryPercent.Value, Model.DecimalPlaces) + "%")</td>
    }
    else
    {
        <td class="text-muted">?</td>
    }
}

src/Opserver.Web/Views/Shared/TopRefresh.cshtml
@model Opserver.Views.Shared.TopRefreshModel
<div>
    <partial name="TopTabs" model="Model.Tab" />
</div>
<ul>
    <partial name="IssuesButton" />
</ul>

src/Opserver.Web/Views/Shared/TopTabs.cshtml
@using StackExchange.Profiling
@functions
{
    void RenderTab(NavTab tab)
    {
        if (tab.IsEnabled)
        {
            // Optimism!
            using (MiniProfiler.Current.Step("Render Tab: " + tab.Name))
            {
                <li class="@(tab == Current.NavTab ? "active" : null)">
                    <a href="@Url.Content(tab.Route)" title="@tab.Tooltip">
                        <span class="@(tab.Module.MonitorStatus.TextClass())">@tab.Name</span>
                        @if (tab.BadgeCount > 0)
                        {
                            <span class="badge" data-name="@tab.Name">@tab.BadgeCount.ToComma()</span>
                        }
                    </a>
                </li>
            }
        }
    }
}
@using (MiniProfiler.Current.Step("TopTabs"))
{
    <ul class="nav navbar-nav navbar-right js-top-tabs">
        @foreach (var tab in NavTab.AllTabs)
        {
            RenderTab(tab);
        }
    </ul>
}