src/Opserver.Web/Controllers/HAProxyController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Opserver.Data.HAProxy;
using Opserver.Helpers;
using Opserver.Views.HAProxy;

namespace Opserver.Controllers
{
    [OnlyAllow(HAProxyRoles.Viewer)]
    public partial class HAProxyController : StatusController<HAProxyModule>
    {
        public HAProxyController(HAProxyModule module, IOptions<OpserverSettings> settings) : base(module, settings) { }

        [DefaultRoute("haproxy")]
        public ActionResult Dashboard(string group, string node, string watch = null, bool norefresh = false)
        {
            var haGroup = Module.GetGroup(group ?? node);
            var proxies = haGroup != null ? haGroup.GetProxies() : Module.GetAllProxies();
            proxies.RemoveAll(p => !p.HasServers);

            var vd = new HAProxyModel
            {
                SelectedGroup = haGroup,
                Groups = haGroup != null ? new List<HAProxyGroup> { haGroup } : Module.Groups,
                Proxies = proxies,
                View = HAProxyModel.Views.Dashboard,
                Refresh = !norefresh,
                WatchProxy = watch
            };
            return View("HAProxy.Dashboard", vd);
        }
    }
}

src/Opserver.Web/Controllers/RedisController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Opserver.Data.Redis;
using Opserver.Helpers;
using Opserver.Views.Redis;

namespace Opserver.Controllers
{
    [OnlyAllow(RedisRoles.Viewer)]
    public partial class RedisController : StatusController<RedisModule>
    {
        public RedisController(RedisModule module, IOptions<OpserverSettings> settings) : base(module, settings) { }

        [DefaultRoute("redis")]
        public ActionResult Dashboard(string node)
        {
            var instances = Module.GetAllInstances(node);
            if (instances.Count == 1 && instances[0] != null)
            {
                // In the 1 case, redirect
                return RedirectToAction(nameof(Instance), new { node });
            }
            var vd = new DashboardModel
            {
                ReplicationGroups = Module.ReplicationGroups,
                Instances = instances.Count > 1 ? instances : Module.Instances,
                View = node.HasValue() ? RedisViews.Server : RedisViews.All,
                CurrentRedisServer = node,
                Refresh = true
            };
            return View("Dashboard.Instances", vd);
        }

        [Route("redis/instance")]
        public ActionResult Instance(string node)
        {
            var instance = Module.GetInstance(node);

            var vd = new DashboardModel
            {
                Instances = Module.Instances,
                CurrentInstance = instance,
                View = RedisViews.Instance,
                CurrentRedisServer = node,
                Refresh = true
            };
            return View(vd);
        }

        [Route("redis/instance/get-config/{host}-{port}-config.zip")]
        public ActionResult DownloadConfiguration(string host, int port)
        {
            var instance = Module.GetInstance(host, port);
            var configZip = instance.GetConfigZip();
            return new FileContentResult(configZip, "application/zip");
        }

        [Route("redis/instance/summary/{type}")]
        public ActionResult InstanceSummary(string node, string type)
        {
            var i = Module.GetInstance(node);
            if (i == null) return ContentNotFound("Could not find instance " + node);

            return type switch
            {
                "config" => PartialView("Instance.Config", i),
                "clients" => PartialView("Instance.Clients", i),
                "info" => PartialView("Instance.Info", i),
                "slow-log" => PartialView("Instance.SlowLog", i),
                _ => ContentNotFound("Unknown summary view requested"),
            };
        }

        [Route("redis/analyze/memory")]
        public ActionResult Analysis(string node, int db, bool runOnMaster = false)
        {
            var instance = Module.GetInstance(node);
            if (instance == null)
                return TextPlain("Instance not found");
            var analysis = instance.GetDatabaseMemoryAnalysis(db, runOnMaster);

            return View("Instance.Analysis.Memory", analysis);
        }

        [Route("redis/analyze/memory/clear")]
        public ActionResult ClearAnalysis(string node, int db)
        {
            var instance = Module.GetInstance(node);
            if (instance == null)
                return TextPlain("Instance not found");
            instance.ClearDatabaseMemoryAnalysisCache(db);

            return RedirectToAction(nameof(Analysis), new { node, db });
        }
    }
}

src/Opserver.Web/Controllers/SQLController.cs
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Options;
using Opserver.Data.SQL;
using Opserver.Helpers;
using Opserver.Views.SQL;

namespace Opserver.Controllers
{
    [OnlyAllow(SQLRoles.Viewer)]
    public partial class SQLController : StatusController<SQLModule>
    {
        public SQLController(SQLModule sqlModule, IOptions<OpserverSettings> settings) : base(sqlModule, settings) { }

        [DefaultRoute("sql")]
        public ActionResult Dashboard() => RedirectToAction(nameof(Servers));

        [Route("sql/servers")]
        public ActionResult Servers(string cluster, string node, string ag, bool detailOnly = false)
        {
            var vd = new ServersModel
                {
                    AzureServers = Module.AzureServers,
                    StandaloneInstances = Module.StandaloneInstances,
                    Clusters = Module.Clusters,
                    Refresh = node.HasValue() ? 10 : 5
                };


            if (cluster.HasValue())
                vd.CurrentCluster = vd.Clusters.Find(c => string.Equals(c.Name, cluster, StringComparison.OrdinalIgnoreCase));
            if (vd.CurrentCluster != null)
                vd.AvailabilityGroups = vd.CurrentCluster.GetAvailabilityGroups(node, ag).ToList();

            if (detailOnly && vd.CurrentCluster != null)
                return PartialView("Servers.ClusterDetail", vd);

            return View("Servers", vd);
        }

        [Route("sql/jobs")]
        public ActionResult AllJobs(JobSort? sort = null, SortDir? dir = null)
        {
            var vd = new ServersModel
            {
                View = SQLViews.Jobs,
                AzureServers = Module.AzureServers,
                StandaloneInstances = Module.StandaloneInstances,
                Clusters = Module.Clusters,
                Refresh = 30,
                JobSort = sort,
                SortDirection = dir
            };

            return View("AllJobs", vd);
        }

        [Route("sql/instance")]
        public ActionResult Instance(string node)
        {
            var i = Module.GetInstance(node);
            var vd = new InstanceModel
            {
                View = SQLViews.Instance,
                Refresh = node.HasValue() ? 10 : 5,
                CurrentInstance = i
            };
            return View("Instance", vd);
        }

        [Route("sql/instance/summary/{type}")]
        public ActionResult InstanceSummary(string node, string type)
        {
            var i = Module.GetInstance(node);
            if (i == null) return NoInstanceRedirect(node);

            return type switch
            {
                "configuration" => PartialView("Instance.Configuration", i),
                "connections" => PartialView("Instance.Connections", i),
                "errors" => PartialView("Instance.Errors", i),
                "memory" => PartialView("Instance.Memory", i),
                "jobs" => PartialView("Instance.Jobs", i),
                "db-files" => PartialView("Instance.DBFiles", i),
                _ => ContentNotFound("Unknown summary view requested"),
            };
        }

        [ResponseCache(Duration = 5 * 1, VaryByQueryKeys = new string[] { "node", "sort", "options" }, Location = ResponseCacheLocation.Client)]
        [Route("sql/top")]
        public ActionResult Top(string node, SQLInstance.TopSearchOptions options)
        {
            var vd = GetOperationsModel(node, options);
            var i = vd.CurrentInstance;

            if (i != null)
            {
                var cache = i.GetTopOperations(options);
                vd.TopOperations = cache.Data;
                vd.ErrorMessage = cache.ErrorMessage;
            }

            return View("Operations.Top", vd);
        }

        [Route("sql/top/filters")]
        public ActionResult TopFilters(string node, SQLInstance.TopSearchOptions options) =>
            View("Operations.Top.Filters", GetOperationsModel(node, options));

        private OperationsTopModel GetOperationsModel(string node, SQLInstance.TopSearchOptions options)
        {
            var i = Module.GetInstance(node);
            options.SetDefaults();

            return new OperationsTopModel
            {
                View = SQLViews.Top,
                CurrentInstance = i,
                TopSearchOptions = options
            };
        }

        [Route("sql/top/detail")]
        public ActionResult TopDetail(string node, string handle, int? offset = null)
        {
            var planHandle = WebEncoders.Base64UrlDecode(handle);

            var i = Module.GetInstance(node);

            var vd = new OperationsTopDetailModel
            {
                Instance = i,
                Op = i.GetTopOperation(planHandle, offset).Data
            };
            return PartialView("Operations.Top.Detail", vd);
        }

        [Route("sql/top/plan")]
        public ActionResult TopPlan(string node, string handle)
        {
            var planHandle = WebEncoders.Base64UrlDecode(handle);
            var i = Module.GetInstance(node);
            var op = i.GetTopOperation(planHandle).Data;
            if (op == null) return ContentNotFound("Plan was not found.");

            var ms = new MemoryStream(Encoding.UTF8.GetBytes(op.QueryPlan));

            return File(ms, "text/xml", $"QueryPlan-{Math.Abs(handle.GetHashCode())}.sqlplan");
        }

        [Route("sql/active")]
        public ActionResult Active(string node, SQLInstance.ActiveSearchOptions options) =>
            View("Operations.Active", GetOperationsActiveModel(node, options));

        [Route("sql/active/filters")]
        public ActionResult ActiveFilters(string node, SQLInstance.ActiveSearchOptions options) =>
            View("Operations.Active.Filters", GetOperationsActiveModel(node, options));

        private OperationsActiveModel GetOperationsActiveModel(string node, SQLInstance.ActiveSearchOptions options)
        {
            var i = Module.GetInstance(node);
            return new OperationsActiveModel
            {
                View = SQLViews.Active,
                CurrentInstance = i,
                ActiveSearchOptions = options
            };
        }

        [Route("sql/connections")]
        public async Task<ActionResult> Connections(string node)
        {
            var i = Module.GetInstance(node);
            var vd = new DashboardModel
            {
                View = SQLViews.Connections,
                CurrentInstance = i,
                Cache = i?.Connections,
                Connections = i == null ? null : await i.Connections.GetData()
            };
            return View(vd);
        }

        [Route("sql/databases")]
        public ActionResult Databases(string node)
        {
            var i = Module.GetInstance(node);
            var vd = new DashboardModel
            {
                View = SQLViews.Databases,
                CurrentInstance = i,
                Refresh = 2*60
            };
            return View(vd);
        }

        [Route("sql/db/{database}/{view}")]
        [Route("sql/db/{database}/{view}/{objectName}")]
        public ActionResult DatabaseDetail(string node, string database, string view, string objectName)
        {
            var i = Module.GetInstance(node);
            var vd = new DatabasesModel
            {
                Instance = i,
                Database = database,
                ObjectName = objectName
            };
            switch (view)
            {
                case "backups":
                    vd.View = DatabasesModel.Views.Backups;
                    return View("Databases.Modal.Backups", vd);
                case "restores":
                    vd.View = DatabasesModel.Views.Restores;
                    return View("Databases.Modal.Restores", vd);
                case "storage":
                    vd.View = DatabasesModel.Views.Storage;
                    return View("Databases.Modal.Storage", vd);
                case "tables":
                    vd.View = DatabasesModel.Views.Tables;
                    return View("Databases.Modal.Tables", vd);
                case "views":
                    vd.View = DatabasesModel.Views.Views;
                    return View("Databases.Modal.Views", vd);
                case "unusedindexes":
                    vd.View = DatabasesModel.Views.UnusedIndexes;
                    return View("Databases.Modal.UnusedIndexes", vd);
                case "missingindexes":
                    vd.View = DatabasesModel.Views.MissingIndexes;
                    return View("Databases.Modal.MissingIndexes", vd);
                case "storedprocedures":
                    vd.View = DatabasesModel.Views.StoredProcedures;
                    return View("Databases.Modal.StoredProcedures", vd);
            }
            return View("Databases.Modal.Tables", vd);
        }

        [Route("sql/databases/tables")]
        public ActionResult DatabaseTables(string node, string database)
        {
            var i = Module.GetInstance(node);
            var vd = new DatabasesModel
            {
                Instance = i,
                Database = database
            };
            return View("Databases.Modal.Tables", vd);
        }

        private ActionResult NoInstanceRedirect(string node) =>
            Request.IsAjax()
            ? ContentNotFound("Instance " + node + " was not found.")
            : (ActionResult)View("Instance.Selector", new DashboardModel());
    }
}

src/Opserver.Web/Views/Dashboard/Dashboard.Table.cshtml
@using StackExchange.Profiling
@inject IJsonHelper Json
@model DashboardModel
@{
    // Note: not using MVC Url.Action and such here because it's too slow
    Layout = "Dashboard.cshtml";
    var categories = Model.Nodes
                          .GroupBy(n => n.Category)
                          .Where(g => g.Any() && (g.Key != DashboardCategory.Unknown || Module.Settings.ShowOther))
                          .OrderBy(g => g.Key.Index);
}
@section preload {
    @if (Module.HasData && this.SupportsSvgViewport())
    {
        <link rel="preload" href="@Url.Content("~/graph/")cpu/spark/all" as="image">
        <link rel="preload" href="@Url.Content("~/graph/")memory/spark/all" as="image">
        <link rel="preload" href="@Url.Content("~/graph/")network/spark/all" as="image">
    }
}
@functions
{
    string Graph(Node n, string type)
    {
        if (Module.HasData)
        {
            if (this.SupportsSvgViewport())
            {
                <a href="#/dashboard/graph/@(n.Id.UrlEncode())/@type"><img src="@Url.Content("~/graph/")@type/spark/all#@n.Id" alt="" /></a>
            }
            else
            {
                <a href="#/dashboard/graph/@(n.Id.UrlEncode())/@type"><img src="@Url.Content("~/graph/")@type/spark?id=@n.Id" alt="" /></a>
            }
        }
        else
        {
            <div class="text-muted">No Data Available</div>
        }
        return null;
    }

    string DiskText(Node n)
    {
        var worst = n.Volumes?.Where(v => v?.PercentUsed.HasValue ?? false).DefaultIfEmpty().Max(v => v?.PercentUsed);
        if (worst > 0)
        {
            @worst.Value.ToString("n0")@:%
        }
        return null;
    }

    string DiskGraphs(Node n)
    {
        if (n.Volumes != null)
        {
            for (var i = 0; i < n.Volumes.Count && i < 10; i++)
            {
                var vol = n.Volumes[i];
                <div class="progress vertical" title="@vol.PrettyName: @(vol.PercentUsed?.ToString("n2"))% used (@vol.PrettyUsed/@vol.PrettySize)">
                    <div class="progress-bar @vol.SpaceStatus.ProgressBarClass()" style="height: @(vol.PercentUsed?.ToString("n2",CultureInfo.InvariantCulture))%"></div>
                </div>
            }
        }
        return null;
    }
}
<div class="js-refresh" data-name="dashboard-overview">
    @if (!Model.Nodes.Any() || Model.IsStartingUp)
    {
        var errors = Model.ErrorMessages;
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center" style="margin-top: 100px">
                @if (Model.IsStartingUp)
                {
                    <h5>No data, yet!</h5>
                    <p class="text-muted small">The initial poll is underway - you'll see nodes appear in just a moment.</p>
                    <div class="sk-wave"><div></div><div></div><div></div><div></div><div></div></div>
                    <script>Status.refresh.schedule(2000);</script>
                }
                else
                {
                    <p>No nodes available</p>
                }
            </div>
        </div>
        if (errors != null && errors.Any())
        {
            <script>
                @foreach (var e in errors)
                {
                    @:toastr.warning('@Json.Serialize(e)', null, { positionClass: "toast-bottom-full-width", timeOut: 60 * 1000 });
                }
            </script>
        }
    }
    else
    {
        <table class="table table-striped table-responsive table-middle table-super-condensed table-dashboard text-nowrap js-nodes">
            @foreach (var g in categories)
            {
                var c = g.Key;
                using (MiniProfiler.Current.Step("Category: " + c.Name))
                {
                    <tbody>
                        <tr class="category-row">
                            <th colspan="9">
                                <h5>@c.Name</h5>
                            </th>
                        </tr>
                        <tr>
                            <th>Node</th>
                            <th colspan="2">CPU</th>
                            <th colspan="2">Memory</th>
                            <th colspan="2">Network</th>
                            @if (Module.Settings.ShowVolumePerformance)
                            {
                                <th colspan="2">Disk (Perf)</th>
                            }
                            <th colspan="2">Disk</th>
                        </tr>
                        @foreach (var n in g.OrderBy(n => n.PrettyName))
                        {
                            <tr class="@(n.RowClass().Nullify())@(n.IsVM ? " virtual-machine" : null)@(n.IsUnwatched ? " unwatched-row" : null)" data-node="@n.PrettyName">
                                <td title="@(n.IsVM ? "Virtual Machine hosted on " + (n.VMHost?.PrettyName ?? "Unknown") + " " : null)Last Updated: @(n.LastSync?.ToRelativeTime())">
                                    @n.IconSpan()
                                    <a href="~/dashboard/node?node=@n.PrettyName" class="@n.TextClass().Nullify()">@n.PrettyName</a>
                                </td>
                                <td class="@n.CPUMonitorStatus().TextClass().Nullify()">@(n.CPULoad?.ToString("n0")) %</td>
                                <td>@Graph(n, "cpu")</td>
                                <td>
                                    <span class="@n.MemoryMonitorStatus().TextClass().Nullify()">@n.PrettyMemoryUsed() / @n.PrettyTotalMemory() (@(n.PercentMemoryUsed?.ToString("n2"))%)</span>
                                    @if (n.MemoryUsed >= 0)
                                    {
                                        <div class="progress" style="width: 215px;">
                                            <div class="progress-bar @n.MemoryMonitorStatus().ProgressBarClass()" style="width: @(n.PercentMemoryUsed?.ToString("n2",CultureInfo.InvariantCulture))%"></div>
                                        </div>
                                    }
                                </td>
                                <td>@Graph(n, "memory")</td>
                                <td>@n.PrettyTotalNetwork()</td>
                                <td>@Graph(n, "network")</td>
                                @if (Module.Settings.ShowVolumePerformance)
                                {
                                    <td>@n.PrettyTotalVolumePerformance()</td>
                                    <td>@Graph(n, "volumePerformance")</td>
                                }
                                <td>@DiskText(n)</td>
                                <td>@DiskGraphs(n)</td>
                            </tr>
                        }
                    </tbody>
                }
            }
        </table>
    }
</div>

src/Opserver.Web/Views/Dashboard/Node.VMHost.cshtml
@model Node
<partial name="Dashboard.Table" model="new DashboardModel { Nodes = Model.VMs }" />

src/Opserver.Web/Views/Dashboard/Node.cshtml
@inject Opserver.Data.Elastic.ElasticModule Elastic
@inject Opserver.Data.HAProxy.HAProxyModule HAProxy
@inject Opserver.Data.Redis.RedisModule Redis
@inject Opserver.Data.SQL.SQLModule Sql
@model NodeModel
@{
    var s = Model.CurrentNode;

    this.SetPageTitle((s?.PrettyName ?? "Unknown Node") + " Status");
    this.SetTopNodes(Module.AllNodes, "Dashboard", Model.CurrentNode);

    if (Model.CurrentStatusType.HasValue && !StatusTypes.Contains(Model.CurrentStatusType.Value))
    {
        // Sanity check, needs to happen here due to DI order at the moment
        Model.CurrentStatusType = null;
    }
}
@section head {
    <script>
        $(function () {
            Status.Dashboard.init({ refresh: false });
            Status.Dashboard.Server.init({ node: '@(s?.PrettyName)' });
        });
    </script>
}
@functions
{
    void SubnavItem(CurrentStatusTypes st, string url, bool isExternal = true)
    {
        <li class="@(Model.CurrentStatusType == st ? "active" : "")@(isExternal ? " exit-link" : null)"><a href="@url">@st.AsString(EnumFormat.Description)</a></li>
    }
    public IEnumerable<CurrentStatusTypes> StatusTypes
    {
        get
        {
            var node = Model.CurrentNode;
            if (node == null) yield break;

            // TODO: Move to a method that takes a list of modules instead, and gets types from each.
            // Where these "types" should be defined is a question though - an enum isn't extensible for plugins later

            yield return CurrentStatusTypes.Stats;

            // TODO: Redis, SQL, etc node recognition - more pluggable?
            // Need to nuke the enum here...
            if (Sql.IsMember(node))
            {
                yield return CurrentStatusTypes.SQLInstance;
                yield return CurrentStatusTypes.SQLTop;
                yield return CurrentStatusTypes.SQLActive;
            }
            if (Redis.IsMember(node))
            {
                yield return CurrentStatusTypes.Redis;
            }
            if (Elastic.IsMember(node))
            {
                yield return CurrentStatusTypes.Elastic;
            }
            if (HAProxy.IsMember(node))
            {
                yield return CurrentStatusTypes.HAProxy;
            }
            if (Model.CurrentNode.IsVMHost)
                yield return CurrentStatusTypes.VMHost;
            //if (CurrentNode.Interfaces.Any())
            //    yield return CurrentStatusTypes.Interfaces;
        }
    }
}
@if (s == null)
{
    <div class="no-content">Node not found.</div>
    return;
}
<h5 class="page-header">
    <span title="Status: @s.Status.AsString(EnumFormat.Description)">@s.IconSpan()</span>
    @s.PrettyName
    @if (s.IsVM)
    {
        <span class="text-muted">(Virtual Machine)</span>
    }
    @if (s.ManagementUrl.HasValue())
    {
        <span class="small text-muted">(<a href="@s.ManagementUrl" target="_blank">View in @s.DataProvider.Name</a>)</span>
    }
    <span class="pull-right small" title="@if (s.PollIntervalSeconds.HasValue){<text>Polling Interval: @(s.PollInterval?.ToReadableString())</text>}">
        As of @s.LastUpdatedSpan()
    </span>
</h5>
<div class="row small">
    <div class="col-md-4 col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Info
                @if (s.Hardware != null)
                {
                    <span class="text-muted">(<a href="#/dashboard/summary/hardware">view hardware</a>)</span>
                }
            </div>
            <div class="panel-body">
                <div class="value-block small col-xs-6">
                    @if (s.Manufacturer.IsNullOrEmpty() && s.VMHost != null)
                    {
                        <a href="@Url.Action(nameof(DashboardController.Node), new {node = s.VMHost.PrettyName, view = CurrentStatusTypes.VMHost})">@s.VMHost.PrettyName</a>
                        <label>VM Host</label>
                    }
                    else
                    {
                        @s.Manufacturer.IsNullOrEmptyReturn("Unknown")
                        <label>Manufacturer</label>
                    }
                </div>
                <div class="value-block small col-xs-6">
                    @s.Model.IsNullOrEmptyReturn("Unknown")
                    <label>Model</label>
                </div>
                <div class="value-block small col-xs-6">
                    @s.ServiceTag.IsNullOrEmptyReturn("Unknown")
                    <label>Serial</label>
                </div>
                <div class="value-block small col-xs-6" title="@s.MachineType">
                    @s.MachineTypePretty.IsNullOrEmptyReturn("Unknown")
                    <label>Type</label>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Stats
                @if (s.IsRealTimePollable)
                {
                    //<span class="text-muted">(<a href="#/dashboard/graph/@s.Id.UrlEncode()/@NodeGraphModel.KnownTypes.Live" class="js-realtime-cpu">live</a>)</span>
                }
            </div>
            <div class="panel-body">
                <div class="value-block small col-xs-6" title="@s.ApplicationCPUTextSummary.Nullify()">
                    <div class="progress">
                        <div class="progress-bar" style="width: @(s.CPULoad?.ToString(CultureInfo.InvariantCulture))%;"></div>
                        <span>@s.CPUStatusSpan()</span>
                    </div>
                    <label>CPU</label>
                </div>
                <div class="value-block small col-xs-6" title="@s.ApplicationMemoryTextSummary.Nullify()">
                    <div class="progress">
                        <div class="progress-bar @s.MemoryMonitorStatus().ProgressBarClass()" style="width: @(s.PercentMemoryUsed?.ToString(CultureInfo.InvariantCulture))%;"></div>
                        <span>@s.PrettyMemoryUsed() / @s.PrettyTotalMemory()</span>
                    </div>
                    <label>Memory</label>
                </div>
                <div class="value-block small col-xs-6" title="@s.NetworkTextSummary.Nullify()">
                    @s.PrettyTotalNetwork()
                    <label>
                        Network
                        @{
                            var ips = s.IPs;
                            <span class="text-muted">(<a href="#/dashboard/summary/network">@(ips?.Any() ?? false ? ips.Count.Pluralize("IP") : "view" )</a>)</span>
                        }
                    </label>
                </div>
                <div class="value-block small col-xs-6">
                    @if (s.LastBoot != null)
                    {
                        <span title="@DateTime.UtcNow.ToRelativeTime(compareTo: s.LastBoot, asPlusMinus: true, includeSign: false) ago">
                            @(s.LastBoot?.ToRelativeTimeSpan())
                        </span>
                    }
                    else
                    {
                        <span class="text-warning">Unknown</span>
                    }
                    <label>Last Boot</label>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">Storage</div>
            <div class="panel-body">
                @if (s.Volumes != null)
                {
                    foreach (var v in s.Volumes.Where(vol => vol.IsDisk && vol.Size > 0))
                    {
                        <div class="value-block small col-xs-12" title="@v.Description: @(v.Used?.ToString("n0")) of @(v.Size?.ToString("n0")) bytes used">
                            <div class="progress">
                                <div class="progress-bar @(v.SpaceStatus.ProgressBarClass())" style="width: @(v.PercentUsed?.ToString(CultureInfo.InvariantCulture))%;"></div>
                                <span>@v.PrettyDescription - (@v.PrettyUsed / @v.PrettySize) - <span class="@v.SpaceStatus.TextClass()">@v.PercentFreeSpace()</span></span>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>
@if (StatusTypes.Count() > 1)
{ // only show nav if there's actual nav - save the vertical space on stats-only nodes
    <ul class="nav nav-tabs nav-tabs-right">
        @foreach (var st in StatusTypes.OrderBy(i => i))
        {
            // TODO: Re-vamp this whole section
            switch (st)
            {
                case CurrentStatusTypes.SQLInstance:
                    SubnavItem(st, Url.Action(nameof(SQLController.Instance), "SQL", new { node = s.PrettyName }));
                    break;
                case CurrentStatusTypes.SQLActive:
                    SubnavItem(st, Url.Action(nameof(SQLController.Active), "SQL", new { node = s.PrettyName }));
                    break;
                case CurrentStatusTypes.SQLTop:
                    SubnavItem(st, Url.Action(nameof(SQLController.Top), "SQL", new { node = s.PrettyName }));
                    break;
                case CurrentStatusTypes.Redis:
                    SubnavItem(st, Url.Action(nameof(RedisController.Dashboard), "Redis", new { node = s.PrettyName }));
                    break;
                case CurrentStatusTypes.HAProxy:
                    SubnavItem(st, Url.Action(nameof(HAProxyController.Dashboard), "HAProxy", new { node = s.PrettyName }));
                    break;
                //case CurrentStatusTypes.Elastic:
                //SubnavItem(st, "/elastic" + s.PrettyName);
                //break;
                default:
                    SubnavItem(st, Url.Action(nameof(DashboardController.Node), new { node = s.PrettyName, view = st }));
                    break;
            }
        }
    </ul>
}
<div data-node="@Model.CurrentNode.PrettyName">
    @if (Model.CurrentStatusType != CurrentStatusTypes.None)
    {
        <partial name="@("Node." + Model.CurrentStatusType)" model="s" />
    }
</div>